<a href="https://colab.research.google.com/github/thisismemayanka/analysis-projects/blob/main/5_Difference_in_difference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip -q install requests pandas matplotlib seaborn statsmodels

In [ ]:
import requests
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.formula.api as smf

from google.colab import userdata

sns.set_style("whitegrid")
pd.set_option("display.max_columns", None)

In [ ]:
API_KEY = userdata.get("openaq")

headers = {
    "X-API-Key": API_KEY
}

print("API Key Loaded Successfully")

API Key Loaded Successfully

In [ ]:
all_locations = []

page = 1

while True:

    params = {
        "country_id": 91,
        "limit": 1000,
        "page": page
    }

    response = requests.get(
        "https://api.openaq.org/v3/locations",
        headers=headers,
        params=params
    )

    response.raise_for_status()

    results = response.json()["results"]

    if len(results) == 0:
        break

    all_locations.extend(results)

    print(f"Downloaded Page {page} ({len(results)} locations)")

    page += 1

df_locations = pd.json_normalize(all_locations)

print("\nTotal Locations :", len(df_locations))

Downloaded Page 1 (1000 locations)
Downloaded Page 2 (1000 locations)
Downloaded Page 3 (1000 locations)
Downloaded Page 4 (1000 locations)
Downloaded Page 5 (1000 locations)
Downloaded Page 6 (1000 locations)
Downloaded Page 7 (1000 locations)
Downloaded Page 8 (1000 locations)
Downloaded Page 9 (1000 locations)
Downloaded Page 10 (1000 locations)
Downloaded Page 11 (1000 locations)
Downloaded Page 12 (1000 locations)
Downloaded Page 13 (1000 locations)
Downloaded Page 14 (1000 locations)
Downloaded Page 15 (1000 locations)
Downloaded Page 16 (1000 locations)
Downloaded Page 17 (1000 locations)
Downloaded Page 18 (1000 locations)
Downloaded Page 19 (1000 locations)
Downloaded Page 20 (1000 locations)
Downloaded Page 21 (1000 locations)
Downloaded Page 22 (1000 locations)
Downloaded Page 23 (1000 locations)
Downloaded Page 24 (1000 locations)
Downloaded Page 25 (900 locations)

Total Locations : 24900

In [ ]:
cities = [
    "Delhi",
    "New Delhi",
    "Noida",
    "Ghaziabad",
    "Faridabad",
    "Gurugram",
    "Gurgaon"
]

pattern = "|".join(cities)

stations = df_locations[
    df_locations["name"].str.contains(
        pattern,
        case=False,
        na=False
    )
].copy()

stations[[
    "id",
    "name",
    "coordinates.latitude",
    "coordinates.longitude"
]]

,id,name,coordinates.latitude,coordinates.longitude
10,13,"Delhi Technological University, Delhi - CPCB",28.744000,77.120000
14,17,"R K Puram, Delhi - DPCC",28.563262,77.186937
41,50,"Punjabi Bagh, Delhi - DPCC",28.674045,77.131023
83,103,"Income Tax Office, Delhi - CPCB",28.623500,77.249400
180,235,"Anand Vihar, New Delhi - DPCC",28.646835,77.316032
...,...,...,...,...
23776,6254665,"Commonwealth Sports Complex, Delhi - DPCC",28.615828,77.271992
23777,6254666,"IGNOU_Maidan Garhi, Delhi - DPCC",28.493624,77.201159
23789,6257818,"Cantonment Area, Delhi - DPCC",28.594169,77.125100
24111,6299678,"Ved Vihar-Loni, Ghaziabad - UPPCB",28.739153,77.273668
24219,6311324,"Govindpuram, Ghaziabad - UPPCB",28.694528,77.494705

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
sensor_rows = []

for _, row in stations.iterrows():

    sensors = row["sensors"]

    if isinstance(sensors, list):

        for sensor in sensors:

            parameter = sensor.get("parameter", {}).get("name")

            if parameter == "pm25":

                sensor_rows.append({

                    "location_id": row["id"],

                    "station": row["name"],

                    "sensor_id": sensor["id"]

                })

sensor_df = pd.DataFrame(sensor_rows)

sensor_df

     location_id                                            station  sensor_id
0             13       Delhi Technological University, Delhi - CPCB      13864
1             17                            R K Puram, Delhi - DPCC         35
2             17                            R K Puram, Delhi - DPCC   12234787
3             50                         Punjabi Bagh, Delhi - DPCC        396
4             50                         Punjabi Bagh, Delhi - DPCC   12234796
5            103                    Income Tax Office, Delhi - CPCB      13861
6            235                      Anand Vihar, New Delhi - DPCC        384
7            235                      Anand Vihar, New Delhi - DPCC   12235610
8            236                          Mandir Marg, Delhi - DPCC        388
9            301                      Vikas Sadan, Gurugram - HSPCB       1166
10           301                      Vikas Sadan, Gurugram - HSPCB   14258988
11           431                                IHBAS, Delhi - CPCB      13868
12          2503                             Shadipur, Delhi - CPCB      13860
13          2587                       Sector16A, Faridabad - HSPCB      13900
14          2597                      US Diplomatic Post: New Delhi       5398
15          5404                                  Pusa, Delhi - IMD   12234702
16          5404                                  Pusa, Delhi - IMD      14087
17          5509                          Anand Vihar, Delhi - DPCC      14521
18          5540                         Punjabi Bagh, Delhi - DPCC      14617
19          5541                   Burari Crossing, New Delhi - IMD   12234684
20          5541                   Burari Crossing, New Delhi - IMD      14912
21          5570                         Aya Nagar, New Delhi - IMD   12234708
22          5570                         Aya Nagar, New Delhi - IMD      14717
23          5581                              Pusa, New Delhi - IMD      14853
24          5586                             Sirifort, Delhi - CPCB   12234769
25          5598                    Sector - 125, Noida, UP - UPPCB   12235187
26          5610                      North Campus, DU, Delhi - IMD      14860
27          5610                      North Campus, DU, Delhi - IMD   12234690
28          5613                              ITO, New Delhi - CPCB      14878
29          5613                              ITO, New Delhi - CPCB   12234753
30          5616                       Sector - 62, Noida, UP - IMD   12234720
31          5617                     Sector- 16A, Faridabad - HSPCB      14930
32          5622                          NSIT Dwarka, Delhi - CPCB      14922
33          5622                          NSIT Dwarka, Delhi - CPCB   12234744
34          5626                              DTU, New Delhi - CPCB   12234760
35          5626                              DTU, New Delhi - CPCB      14985
36          5627                 CRRI Mathura Road, New Delhi - IMD      14935
37          5627                 CRRI Mathura Road, New Delhi - IMD   12234678
38          5630                             Shadipur, Delhi - CPCB   12234726
39          5630                             Shadipur, Delhi - CPCB      14959
40          5634                        Lodhi Road, New Delhi - IMD   12234714
41          5634                        Lodhi Road, New Delhi - IMD      14984
42          5639                        R K Puram, New Delhi - DPCC      15071
43          5641                      Mandir Marg, New Delhi - DPCC      15014
44          5650                      IGI Airport (T3), Delhi - IMD   12234696
45          5665                      Vasundhara, Ghaziabad - UPPCB      15239
46          5665                      Vasundhara, Ghaziabad - UPPCB   12235160
47          5742                           Patparganj, Delhi - DPCC      15629
48          5743                               Rohini, Delhi - DPCC      15618
49          5744       Dr. Karni Singh Shooting Range, Delhi - DPCC      15589
50          5753                          Vivek Vihar, Delhi - DPCC      15604
51          5754             Jawaharlal Nehru Stadium, Delhi - DPCC      15620
52          5755   Major Dhyan Chand National Stadium, Delhi - DPCC      15551
53          5759                          Sonia Vihar, Delhi - DPCC      15595
54          5760                     Dwarka-Sector 8, Delhi - DPCC       15570
55          5761                         Jahangirpuri, Delhi - DPCC      15621
56          5762                          Ashok Vihar, Delhi - DPCC      15602
57          5763                               Narela, Delhi - DPCC      15606
58          5765                        Okhla Phase-2, Delhi - DPCC      15627
59          5766                          Nehru Nagar, Delhi - DPCC      15626
60          6314                   NISE Gwal Pahari, Gurugram - IMD      17564
61          6356                                 Pusa, Delhi - DPCC   12235321
62          6357                         Punjabi Bagh, Delhi - DPCC      17776
63          6358                      Mandir Marg, New Delhi - DPCC      17770
64          6358                      Mandir Marg, New Delhi - DPCC   12234778
65          6359             IHBAS, Dilshad Garden,New Delhi - CPCB   12234735
66          6359             IHBAS, Dilshad Garden,New Delhi - CPCB      17790
67          6924                     Indirapuram, Ghaziabad - UPPCB      19884
68          6924                     Indirapuram, Ghaziabad - UPPCB   12235779
69          6929   Major Dhyan Chand National Stadium, Delhi - DPCC      19900
70          6929   Major Dhyan Chand National Stadium, Delhi - DPCC   12235047
71          6931                     Dwarka-Sector 8, Delhi - DPCC       20150
72          6931                     Dwarka-Sector 8, Delhi - DPCC    12235020
73          6932                               Alipur, Delhi - DPCC   12235698
74          6932                               Alipur, Delhi - DPCC      19935
75          6934       Dr. Karni Singh Shooting Range, Delhi - DPCC   12235011
76          6934       Dr. Karni Singh Shooting Range, Delhi - DPCC      19919
77          6938                          Vivek Vihar, Delhi - DPCC   12235133
78          6938                          Vivek Vihar, Delhi - DPCC      19934
79          6957             Jawaharlal Nehru Stadium, Delhi - DPCC   12235038
80          6957             Jawaharlal Nehru Stadium, Delhi - DPCC      20020
81          6960                           Patparganj, Delhi - DPCC      20049
82          6960                           Patparganj, Delhi - DPCC   12235101
83          6978        Knowledge Park - III, Greater Noida - UPPCB   12235196
84          6978        Knowledge Park - III, Greater Noida - UPPCB      20209
85          6980                            Sector-1, Noida - UPPCB   12235951
86          6980                            Sector-1, Noida - UPPCB      20206
87          6986          Knowledge Park - V, Greater Noida - UPPCB   12235935
88          6986          Knowledge Park - V, Greater Noida - UPPCB      20242
89          6988                          Sector-116, Noida - UPPCB   12235942
90          7005                            Loni, Ghaziabad - UPPCB      20290
91          7005                            Loni, Ghaziabad - UPPCB   12235787
92          7044                            R K Puram, Delhi - DPCC      20411
93          8118                                          New Delhi      23534
94          8235                         Jahangirpuri, Delhi - DPCC      23997
95          8235                         Jahangirpuri, Delhi - DPCC   12235029
96          8239                        Okhla Phase-2, Delhi - DPCC      24007
97          8239                        Okhla Phase-2, Delhi - DPCC   12235074
98          8365                          Nehru Nagar, Delhi - DPCC      35010
99          8365                          Nehru Nagar, Delhi - DPCC   12235083
100         8472                               Bawana, Delhi - DPCC   12235294
101         8472                               Bawana, Delhi - DPCC      36391
102         8475                          Sonia Vihar, Delhi - DPCC      35050
103         8475                          Sonia Vihar, Delhi - DPCC   12235110
104         8915                             Wazirpur, Delhi - DPCC      34731
105         8915                             Wazirpur, Delhi - DPCC   12235124
106         8917                          Ashok Vihar, Delhi - DPCC      26032
107         8917                          Ashok Vihar, Delhi - DPCC   12235002
108        10484                   Sri Aurobindo Marg, Delhi - DPCC   12235312
109        10484                   Sri Aurobindo Marg, Delhi - DPCC      34772
110        10485                               Narela, Delhi - DPCC      34790
111        10485                               Narela, Delhi - DPCC   12235056
112        10486                               Mundka, Delhi - DPCC   12235303
113        10486                               Mundka, Delhi - DPCC      34767
114        10487                          Anand Vihar, Delhi - DPCC      34771
115        10488                            Najafgarh, Delhi - DPCC      34774
116        10488                            Najafgarh, Delhi - DPCC   12235065
117        10489                                  ITO, Delhi - CPCB      35016
118        10820                       Sector 30, Faridabad - HSPCB   12236236
119        10825                        Sector-51, Gurugram - HSPCB      36181
120        10825                        Sector-51, Gurugram - HSPCB   12236259
121        10831                               Rohini, Delhi - DPCC      36399
122        10831                               Rohini, Delhi - DPCC   12235092
123        10900                        Teri Gram, Gurugram - HSPCB   12236251
124        10900                        Teri Gram, Gurugram - HSPCB      36539
125        10908                       Sector 11, Faridabad - HSPCB      36564
126        10908                       Sector 11, Faridabad - HSPCB   12236245
127        10919                    Sanjay Nagar, Ghaziabad - UPPCB   12235770
128        10919                    Sanjay Nagar, Ghaziabad - UPPCB      36675
129        10920             New Industrial Town, Faridabad - HSPCB   12236227
130        10921                   NISE Gwal Pahari, Gurugram - IMD      36701
131        10921                   NISE Gwal Pahari, Gurugram - IMD   12235707
132        11603                        Chandni Chowk, Delhi - IITM      39410
133        11603                        Chandni Chowk, Delhi - IITM   12236361
134        11607                           Lodhi Road, Delhi - IITM   12236376
135        11607                           Lodhi Road, Delhi - IITM      39433
136      3409496                        New Moti Bagh, Delhi - MHUA   15646335
137      6105800                          Sector 1, Noida extension   14453757
138      6119272  Sector - 5, Vasundhara, Ghaziabad, Uttar Pradesh    14551755
139      6148686                            IIT Delhi, Delhi - IITM   14769474
140      6254594                     Talkatora Garden, Delhi - DPCC   15554208
141      6254663                                  JNU, Delhi - DPCC   15554704
142      6254664                       NSUT Jaffarpur, Delhi - DPCC   15554716
143      6254665          Commonwealth Sports Complex, Delhi - DPCC   15554728
144      6254666                   IGNOU_Maidan Garhi, Delhi - DPCC   15554740
145      6257818                      Cantonment Area, Delhi - DPCC   15578291
146      6299678                  Ved Vihar-Loni, Ghaziabad - UPPCB   15890341
147      6311324                     Govindpuram, Ghaziabad - UPPCB   15978433

In [ ]:
import time

def download_sensor(sensor_id,
                    start_date,
                    end_date):

    all_data = []

    page = 1

    while True:

        url = f"https://api.openaq.org/v3/sensors/{sensor_id}/measurements"

        params = {

            "date_from": start_date,

            "date_to": end_date,

            "limit": 1000,

            "page": page

        }

        r = requests.get(
            url,
            headers=headers,
            params=params
        )

        r.raise_for_status()

        results = r.json()["results"]

        if len(results) == 0:
            break

        all_data.extend(results)

        print(
            f"Sensor {sensor_id} | "
            f"Page {page} | "
            f"{len(results)} observations"
        )

        page += 1

        time.sleep(0.2)

    if len(all_data)==0:
        return pd.DataFrame()

    return pd.json_normalize(all_data)

In [ ]:
sensor_df

     location_id                                            station  sensor_id
0             13       Delhi Technological University, Delhi - CPCB      13864
1             17                            R K Puram, Delhi - DPCC         35
2             17                            R K Puram, Delhi - DPCC   12234787
3             50                         Punjabi Bagh, Delhi - DPCC        396
4             50                         Punjabi Bagh, Delhi - DPCC   12234796
5            103                    Income Tax Office, Delhi - CPCB      13861
6            235                      Anand Vihar, New Delhi - DPCC        384
7            235                      Anand Vihar, New Delhi - DPCC   12235610
8            236                          Mandir Marg, Delhi - DPCC        388
9            301                      Vikas Sadan, Gurugram - HSPCB       1166
10           301                      Vikas Sadan, Gurugram - HSPCB   14258988
11           431                                IHBAS, Delhi - CPCB      13868
12          2503                             Shadipur, Delhi - CPCB      13860
13          2587                       Sector16A, Faridabad - HSPCB      13900
14          2597                      US Diplomatic Post: New Delhi       5398
15          5404                                  Pusa, Delhi - IMD   12234702
16          5404                                  Pusa, Delhi - IMD      14087
17          5509                          Anand Vihar, Delhi - DPCC      14521
18          5540                         Punjabi Bagh, Delhi - DPCC      14617
19          5541                   Burari Crossing, New Delhi - IMD   12234684
20          5541                   Burari Crossing, New Delhi - IMD      14912
21          5570                         Aya Nagar, New Delhi - IMD   12234708
22          5570                         Aya Nagar, New Delhi - IMD      14717
23          5581                              Pusa, New Delhi - IMD      14853
24          5586                             Sirifort, Delhi - CPCB   12234769
25          5598                    Sector - 125, Noida, UP - UPPCB   12235187
26          5610                      North Campus, DU, Delhi - IMD      14860
27          5610                      North Campus, DU, Delhi - IMD   12234690
28          5613                              ITO, New Delhi - CPCB      14878
29          5613                              ITO, New Delhi - CPCB   12234753
30          5616                       Sector - 62, Noida, UP - IMD   12234720
31          5617                     Sector- 16A, Faridabad - HSPCB      14930
32          5622                          NSIT Dwarka, Delhi - CPCB      14922
33          5622                          NSIT Dwarka, Delhi - CPCB   12234744
34          5626                              DTU, New Delhi - CPCB   12234760
35          5626                              DTU, New Delhi - CPCB      14985
36          5627                 CRRI Mathura Road, New Delhi - IMD      14935
37          5627                 CRRI Mathura Road, New Delhi - IMD   12234678
38          5630                             Shadipur, Delhi - CPCB   12234726
39          5630                             Shadipur, Delhi - CPCB      14959
40          5634                        Lodhi Road, New Delhi - IMD   12234714
41          5634                        Lodhi Road, New Delhi - IMD      14984
42          5639                        R K Puram, New Delhi - DPCC      15071
43          5641                      Mandir Marg, New Delhi - DPCC      15014
44          5650                      IGI Airport (T3), Delhi - IMD   12234696
45          5665                      Vasundhara, Ghaziabad - UPPCB      15239
46          5665                      Vasundhara, Ghaziabad - UPPCB   12235160
47          5742                           Patparganj, Delhi - DPCC      15629
48          5743                               Rohini, Delhi - DPCC      15618
49          5744       Dr. Karni Singh Shooting Range, Delhi - DPCC      15589
50          5753                          Vivek Vihar, Delhi - DPCC      15604
51          5754             Jawaharlal Nehru Stadium, Delhi - DPCC      15620
52          5755   Major Dhyan Chand National Stadium, Delhi - DPCC      15551
53          5759                          Sonia Vihar, Delhi - DPCC      15595
54          5760                     Dwarka-Sector 8, Delhi - DPCC       15570
55          5761                         Jahangirpuri, Delhi - DPCC      15621
56          5762                          Ashok Vihar, Delhi - DPCC      15602
57          5763                               Narela, Delhi - DPCC      15606
58          5765                        Okhla Phase-2, Delhi - DPCC      15627
59          5766                          Nehru Nagar, Delhi - DPCC      15626
60          6314                   NISE Gwal Pahari, Gurugram - IMD      17564
61          6356                                 Pusa, Delhi - DPCC   12235321
62          6357                         Punjabi Bagh, Delhi - DPCC      17776
63          6358                      Mandir Marg, New Delhi - DPCC      17770
64          6358                      Mandir Marg, New Delhi - DPCC   12234778
65          6359             IHBAS, Dilshad Garden,New Delhi - CPCB   12234735
66          6359             IHBAS, Dilshad Garden,New Delhi - CPCB      17790
67          6924                     Indirapuram, Ghaziabad - UPPCB      19884
68          6924                     Indirapuram, Ghaziabad - UPPCB   12235779
69          6929   Major Dhyan Chand National Stadium, Delhi - DPCC      19900
70          6929   Major Dhyan Chand National Stadium, Delhi - DPCC   12235047
71          6931                     Dwarka-Sector 8, Delhi - DPCC       20150
72          6931                     Dwarka-Sector 8, Delhi - DPCC    12235020
73          6932                               Alipur, Delhi - DPCC   12235698
74          6932                               Alipur, Delhi - DPCC      19935
75          6934       Dr. Karni Singh Shooting Range, Delhi - DPCC   12235011
76          6934       Dr. Karni Singh Shooting Range, Delhi - DPCC      19919
77          6938                          Vivek Vihar, Delhi - DPCC   12235133
78          6938                          Vivek Vihar, Delhi - DPCC      19934
79          6957             Jawaharlal Nehru Stadium, Delhi - DPCC   12235038
80          6957             Jawaharlal Nehru Stadium, Delhi - DPCC      20020
81          6960                           Patparganj, Delhi - DPCC      20049
82          6960                           Patparganj, Delhi - DPCC   12235101
83          6978        Knowledge Park - III, Greater Noida - UPPCB   12235196
84          6978        Knowledge Park - III, Greater Noida - UPPCB      20209
85          6980                            Sector-1, Noida - UPPCB   12235951
86          6980                            Sector-1, Noida - UPPCB      20206
87          6986          Knowledge Park - V, Greater Noida - UPPCB   12235935
88          6986          Knowledge Park - V, Greater Noida - UPPCB      20242
89          6988                          Sector-116, Noida - UPPCB   12235942
90          7005                            Loni, Ghaziabad - UPPCB      20290
91          7005                            Loni, Ghaziabad - UPPCB   12235787
92          7044                            R K Puram, Delhi - DPCC      20411
93          8118                                          New Delhi      23534
94          8235                         Jahangirpuri, Delhi - DPCC      23997
95          8235                         Jahangirpuri, Delhi - DPCC   12235029
96          8239                        Okhla Phase-2, Delhi - DPCC      24007
97          8239                        Okhla Phase-2, Delhi - DPCC   12235074
98          8365                          Nehru Nagar, Delhi - DPCC      35010
99          8365                          Nehru Nagar, Delhi - DPCC   12235083
100         8472                               Bawana, Delhi - DPCC   12235294
101         8472                               Bawana, Delhi - DPCC      36391
102         8475                          Sonia Vihar, Delhi - DPCC      35050
103         8475                          Sonia Vihar, Delhi - DPCC   12235110
104         8915                             Wazirpur, Delhi - DPCC      34731
105         8915                             Wazirpur, Delhi - DPCC   12235124
106         8917                          Ashok Vihar, Delhi - DPCC      26032
107         8917                          Ashok Vihar, Delhi - DPCC   12235002
108        10484                   Sri Aurobindo Marg, Delhi - DPCC   12235312
109        10484                   Sri Aurobindo Marg, Delhi - DPCC      34772
110        10485                               Narela, Delhi - DPCC      34790
111        10485                               Narela, Delhi - DPCC   12235056
112        10486                               Mundka, Delhi - DPCC   12235303
113        10486                               Mundka, Delhi - DPCC      34767
114        10487                          Anand Vihar, Delhi - DPCC      34771
115        10488                            Najafgarh, Delhi - DPCC      34774
116        10488                            Najafgarh, Delhi - DPCC   12235065
117        10489                                  ITO, Delhi - CPCB      35016
118        10820                       Sector 30, Faridabad - HSPCB   12236236
119        10825                        Sector-51, Gurugram - HSPCB      36181
120        10825                        Sector-51, Gurugram - HSPCB   12236259
121        10831                               Rohini, Delhi - DPCC      36399
122        10831                               Rohini, Delhi - DPCC   12235092
123        10900                        Teri Gram, Gurugram - HSPCB   12236251
124        10900                        Teri Gram, Gurugram - HSPCB      36539
125        10908                       Sector 11, Faridabad - HSPCB      36564
126        10908                       Sector 11, Faridabad - HSPCB   12236245
127        10919                    Sanjay Nagar, Ghaziabad - UPPCB   12235770
128        10919                    Sanjay Nagar, Ghaziabad - UPPCB      36675
129        10920             New Industrial Town, Faridabad - HSPCB   12236227
130        10921                   NISE Gwal Pahari, Gurugram - IMD      36701
131        10921                   NISE Gwal Pahari, Gurugram - IMD   12235707
132        11603                        Chandni Chowk, Delhi - IITM      39410
133        11603                        Chandni Chowk, Delhi - IITM   12236361
134        11607                           Lodhi Road, Delhi - IITM   12236376
135        11607                           Lodhi Road, Delhi - IITM      39433
136      3409496                        New Moti Bagh, Delhi - MHUA   15646335
137      6105800                          Sector 1, Noida extension   14453757
138      6119272  Sector - 5, Vasundhara, Ghaziabad, Uttar Pradesh    14551755
139      6148686                            IIT Delhi, Delhi - IITM   14769474
140      6254594                     Talkatora Garden, Delhi - DPCC   15554208
141      6254663                                  JNU, Delhi - DPCC   15554704
142      6254664                       NSUT Jaffarpur, Delhi - DPCC   15554716
143      6254665          Commonwealth Sports Complex, Delhi - DPCC   15554728
144      6254666                   IGNOU_Maidan Garhi, Delhi - DPCC   15554740
145      6257818                      Cantonment Area, Delhi - DPCC   15578291
146      6299678                  Ved Vihar-Loni, Ghaziabad - UPPCB   15890341
147      6311324                     Govindpuram, Ghaziabad - UPPCB   15978433

In [ ]:
selected_sensors = sensor_df[
    sensor_df["station"].isin([
        "Anand Vihar, New Delhi - DPCC",
        "R K Puram, Delhi - DPCC",
        "Vikas Sadan, Gurugram - HSPCB"
    ])
]

selected_sensors

    location_id                        station  sensor_id
1            17        R K Puram, Delhi - DPCC         35
2            17        R K Puram, Delhi - DPCC   12234787
6           235  Anand Vihar, New Delhi - DPCC        384
7           235  Anand Vihar, New Delhi - DPCC   12235610
9           301  Vikas Sadan, Gurugram - HSPCB       1166
10          301  Vikas Sadan, Gurugram - HSPCB   14258988
92         7044        R K Puram, Delhi - DPCC      20411

In [ ]:
import os
import json

RAW_FOLDER = "raw_data"
CHECKPOINT_FOLDER = "checkpoints"

os.makedirs(RAW_FOLDER, exist_ok=True)
os.makedirs(CHECKPOINT_FOLDER, exist_ok=True)

In [ ]:
import os
import json
import time
import requests
import pandas as pd


def download_sensor(
    sensor_id,
    station,
    location_id,
    start_date,
    end_date,
    max_retries=5
):

    csv_file = os.path.join(
        RAW_FOLDER,
        f"sensor_{sensor_id}.csv"
    )

    checkpoint_file = os.path.join(
        CHECKPOINT_FOLDER,
        f"sensor_{sensor_id}.json"
    )

    # Resume support
    start_page = 1

    if os.path.exists(checkpoint_file):

        with open(checkpoint_file, "r") as f:

            checkpoint = json.load(f)

            start_page = checkpoint["last_page"] + 1

            print(
                f"Resuming Sensor {sensor_id} from page {start_page}"
            )

    page = start_page

    while True:

        url = f"https://api.openaq.org/v3/sensors/{sensor_id}/measurements"

        params = {

            "date_from": start_date,

            "date_to": end_date,

            "limit": 1000,

            "page": page

        }

        success = False

        for attempt in range(max_retries):

            try:

                r = requests.get(
                    url,
                    headers=headers,
                    params=params,
                    timeout=90
                )

                r.raise_for_status()

                success = True

                break

            except Exception as e:

                print(
                    f"Retry {attempt+1} "
                    f"Page {page}"
                )

                time.sleep(5)

        if not success:

            print(
                f"Skipping page {page}"
            )

            break

        results = r.json()["results"]

        if len(results) == 0:

            print("Finished sensor.")

            break

        page_df = pd.json_normalize(results)

        page_df["station"] = station
        page_df["location_id"] = location_id
        page_df["sensor_id"] = sensor_id

        page_df.to_csv(

            csv_file,

            mode="a",

            index=False,

            header=not os.path.exists(csv_file)

        )

        with open(checkpoint_file, "w") as f:

            json.dump(
                {

                    "last_page": page

                },
                f
            )

        print(

            f"Sensor {sensor_id}"

            f" Page {page}"

            f" Saved {len(page_df)}"

        )

        page += 1

        time.sleep(1)

In [ ]:
for _, row in selected_sensors.iterrows():

    print("=" * 60)

    print(f"Downloading {row['station']}")

    try:

        download_sensor(

            sensor_id=row["sensor_id"],

            station=row["station"],

            location_id=row["location_id"],

            start_date="2023-10-04",

            end_date="2023-12-02"

        )

    except Exception as e:

        print(e)

        continue

============================================================
Downloading R K Puram, Delhi - DPCC
Resuming Sensor 35 from page 18
Retry 1 Page 18
Retry 2 Page 18
Retry 3 Page 18
Retry 4 Page 18
Retry 5 Page 18
Skipping page 18
============================================================
Downloading R K Puram, Delhi - DPCC
Sensor 12234787 Page 1 Saved 1000
Sensor 12234787 Page 2 Saved 1000
Sensor 12234787 Page 3 Saved 1000
Sensor 12234787 Page 4 Saved 1000
Sensor 12234787 Page 5 Saved 1000
Sensor 12234787 Page 6 Saved 1000
Sensor 12234787 Page 7 Saved 1000
Sensor 12234787 Page 8 Saved 1000
Sensor 12234787 Page 9 Saved 1000
Sensor 12234787 Page 10 Saved 1000
Sensor 12234787 Page 11 Saved 1000
Sensor 12234787 Page 12 Saved 1000
Sensor 12234787 Page 13 Saved 1000
Sensor 12234787 Page 14 Saved 1000
Sensor 12234787 Page 15 Saved 1000
Retry 1 Page 16
Sensor 12234787 Page 16 Saved 1000
Retry 1 Page 17
Retry 2 Page 17
Retry 3 Page 17
Retry 4 Page 17
Retry 5 Page 17
Skipping page 17
============================================================
Downloading Anand Vihar, New Delhi - DPCC
Sensor 12235610 Page 1 Saved 1000
Sensor 12235610 Page 2 Saved 1000
Sensor 12235610 Page 3 Saved 1000
Sensor 12235610 Page 4 Saved 1000
Sensor 12235610 Page 5 Saved 1000
Sensor 12235610 Page 6 Saved 1000
Sensor 12235610 Page 7 Saved 1000
Sensor 12235610 Page 8 Saved 1000
Sensor 12235610 Page 9 Saved 1000
Sensor 12235610 Page 10 Saved 1000
Sensor 12235610 Page 11 Saved 1000
Sensor 12235610 Page 12 Saved 1000
Sensor 12235610 Page 13 Saved 1000
Sensor 12235610 Page 14 Saved 1000
Sensor 12235610 Page 15 Saved 1000
Retry 1 Page 16
Retry 2 Page 16
Retry 3 Page 16
Retry 4 Page 16
Retry 5 Page 16
Skipping page 16
============================================================
Downloading Anand Vihar, New Delhi - DPCC
Sensor 384 Page 1 Saved 1000
Sensor 384 Page 2 Saved 1000
Sensor 384 Page 3 Saved 1000
Sensor 384 Page 4 Saved 1000
Sensor 384 Page 5 Saved 1000
Sensor 384 Page 6 Saved 1000
Sensor 384 Page 7 Saved 1000
Sensor 384 Page 8 Saved 1000
Sensor 384 Page 9 Saved 1000
Sensor 384 Page 10 Saved 1000
Sensor 384 Page 11 Saved 1000
Sensor 384 Page 12 Saved 1000
Sensor 384 Page 13 Saved 1000
Sensor 384 Page 14 Saved 1000
Sensor 384 Page 15 Saved 1000
Retry 1 Page 16
Retry 2 Page 16
Retry 3 Page 16
Retry 4 Page 16
Retry 5 Page 16
Skipping page 16
============================================================
Downloading Vikas Sadan, Gurugram - HSPCB
Sensor 14258988 Page 1 Saved 1000
Sensor 14258988 Page 2 Saved 1000
Sensor 14258988 Page 3 Saved 1000
Sensor 14258988 Page 4 Saved 1000
Sensor 14258988 Page 5 Saved 1000
Sensor 14258988 Page 6 Saved 1000
Sensor 14258988 Page 7 Saved 1000
Retry 1 Page 8
Retry 2 Page 8
Retry 3 Page 8
Retry 4 Page 8
Retry 5 Page 8
Skipping page 8
============================================================
Downloading Vikas Sadan, Gurugram - HSPCB
Sensor 1166 Page 1 Saved 1000
Sensor 1166 Page 2 Saved 1000
Sensor 1166 Page 3 Saved 1000
Sensor 1166 Page 4 Saved 1000
Sensor 1166 Page 5 Saved 1000
Sensor 1166 Page 6 Saved 1000
Sensor 1166 Page 7 Saved 1000
Retry 1 Page 8
Retry 2 Page 8
Retry 3 Page 8
Retry 4 Page 8
Retry 5 Page 8
Skipping page 8
============================================================
Downloading R K Puram, Delhi - DPCC
Sensor 20411 Page 1 Saved 1000
Sensor 20411 Page 2 Saved 1000
Sensor 20411 Page 3 Saved 1000
Sensor 20411 Page 4 Saved 1000
Sensor 20411 Page 5 Saved 1000
Sensor 20411 Page 6 Saved 1000
Sensor 20411 Page 7 Saved 1000
Sensor 20411 Page 8 Saved 1000
Sensor 20411 Page 9 Saved 1000
Sensor 20411 Page 10 Saved 1000
Sensor 20411 Page 11 Saved 1000
Sensor 20411 Page 12 Saved 1000
Sensor 20411 Page 13 Saved 1000
Sensor 20411 Page 14 Saved 1000
Sensor 20411 Page 15 Saved 1000
Sensor 20411 Page 16 Saved 1000
Sensor 20411 Page 17 Saved 1000
Retry 1 Page 18
Retry 2 Page 18
Retry 3 Page 18
Retry 4 Page 18
Retry 5 Page 18
Skipping page 18

In [ ]:
import glob

files = glob.glob("raw_data/*.csv")

print(files)

['raw_data/sensor_1166.csv', 'raw_data/sensor_12235610.csv', 'raw_data/R_K_Puram_Delhi_-_DPCC_20411.csv', 'raw_data/Anand_Vihar_New_Delhi_-_DPCC_384.csv', 'raw_data/R_K_Puram_Delhi_-_DPCC_35.csv', 'raw_data/sensor_12234787.csv', 'raw_data/sensor_35.csv', 'raw_data/sensor_14258988.csv', 'raw_data/sensor_20411.csv', 'raw_data/Vikas_Sadan_Gurugram_-_HSPCB_14258988.csv', 'raw_data/R_K_Puram_Delhi_-_DPCC_12234787.csv', 'raw_data/sensor_384.csv', 'raw_data/Anand_Vihar_New_Delhi_-_DPCC_12235610.csv', 'raw_data/Vikas_Sadan_Gurugram_-_HSPCB_1166.csv']

In [ ]:
dfs = []

for file in files:

    print(file)

    dfs.append(
        pd.read_csv(file)
    )

master = pd.concat(
    dfs,
    ignore_index=True
)

master.to_csv(
    "all_measurements.csv",
    index=False
)

print(master.shape)

raw_data/sensor_1166.csv
raw_data/sensor_12235610.csv
raw_data/sensor_12234787.csv
raw_data/sensor_35.csv
raw_data/sensor_14258988.csv
raw_data/sensor_20411.csv
raw_data/sensor_384.csv
(95000, 27)

In [ ]:
import shutil

shutil.rmtree("checkpoints")